version: "3"

services:
  node1:
    container_name: node1
    image: wachira90/node:14-alpine3.14
    restart: unless-stopped
    working_dir: /var/www/app/
    volumes:
      - ./app:/var/www/app/:rw
#    command: node app.js
    command: sh -c "yarn install && node app.js"
    expose:
      - 5000

  www1:
    container_name: www1
    image: wachira90/nginx:1.21.4
    restart: unless-stopped
    volumes:
      - ./config_nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9001:80

networks:
  default:
